<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator._jkssxx' shared service.

return $this->services['service_locator._jkssxx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['user' => function () {
    $f = function (\AppBundle\Controller\User $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\\Controller\\User']) ? $this->services['AppBundle\\Controller\\User'] : ($this->services['AppBundle\\Controller\\User'] = new \AppBundle\Controller\User())) && false ?: '_'});
}]);
