<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\Task' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\Controller\\Task.php';

return $this->services['AppBundle\\Controller\\Task'] = new \AppBundle\Controller\Task();
