<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBs0m5sg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBs0m5sg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBs0m5sg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBs0m5sg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBs0m5sg\appDevDebugProjectContainer([
    'container.build_hash' => 'Bs0m5sg',
    'container.build_id' => '060b0baa',
    'container.build_time' => 1583778135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBs0m5sg');
