<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9koz8z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9koz8z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE9koz8z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE9koz8z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerE9koz8z\appDevDebugProjectContainer([
    'container.build_hash' => 'E9koz8z',
    'container.build_id' => 'ae12559c',
    'container.build_time' => 1584860812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9koz8z');
